name: Deploy to Cloud Run

on:
  push:
    branches:
      - main
      - master
      - develop
      - engine

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_URI: ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.GCP_REPO_NAME }}/${{ vars.GCP_IMAGE_NAME }}:latest
      CI_COMMIT_HASH: ${{ github.sha }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          install_components: 'beta'

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev

      - name: Generate metadata
        run: |
          echo "CI_DEPLOY_TIMESTAMP=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_ENV
          echo "REVISION_SUFFIX=$(echo '${{ github.ref_name }}' | tr '/' '-' | tr '_' '-' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Go application
        run: |
          GOOS=linux GOARCH=amd64 go build -o app .

      - name: Build Docker image
        run: |
          DOCKER_BUILDKIT=0 docker build -t $IMAGE_URI .

      - name: Push Docker image
        run: |
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ vars.GCP_SERVICE_NAME }} \
            --image=$IMAGE_URI \
            --set-env-vars=CI_DEPLOY_TIMESTAMP=$CI_DEPLOY_TIMESTAMP,CI_COMMIT_HASH=${{ env.CI_COMMIT_HASH }} \
            --region=${{ vars.GCP_REGION }} \
            --platform=managed \
            --allow-unauthenticated